#!/bin/bash
#
#    publish-fash - simples and instants shortcuts for Git and Maven in an interactive script
#    Copyright (C) hdsdi3g for hd3g.tv 2023
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or any
#    later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.
#
#    Usage: just run this script from a maven and git repository
#           you must have a valid setup of:
#             - git
#             - mvn
#             - whiptail
#
#    Update: you can use shellcheck for validate this script
#

set -eu

cmd=(whiptail --title "Fast dev menu" --menu "What do you want to do now?" 0 0 0);
cmd+=("git fetch/pull" "Update the git repo without reset it");
cmd+=("mvn test" "Maven test");
cmd+=("mvn clean" "Maven clean");
cmd+=("mvn install" "Maven install");
cmd+=("mvn package native" "Maven package native-image");
cmd+=("gh pr" "GitHub create PR");
cmd+=("rm repository" "Purge old SNAPSHOTS");
ACTION_LIST=$("${cmd[@]}" 3>&1 1>&2 2>&3);

if [[ "$ACTION_LIST" =~ "git reset/fetch/pull" ]] ; then
	git fetch -p
	# git reset --hard
	git pull
fi

if [[ "$ACTION_LIST" =~ "mvn test" ]] ; then
	mvn test -Djacoco.skip=true -Dlicense.skipAddThirdParty=true -Dagent=false -Dgpg.skip=true -Dmaven.javadoc.skip=true
fi

if [[ "$ACTION_LIST" =~ "mvn clean" ]] ; then
	mvn clean
fi

if [[ "$ACTION_LIST" =~ "mvn install" ]] ; then
	mvn install -DskipTests -Djacoco.skip=true -Dlicense.skipAddThirdParty=true -Dagent=false -Dmaven.javadoc.skip=true
fi

if [[ "$ACTION_LIST" =~ "mvn package native" ]] ; then
	mvn -Pnative clean package -DskipTests -Djacoco.skip=true -Dlicense.skipAddThirdParty=true -Dagent=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
fi

if [[ "$ACTION_LIST" =~ "gh pr" ]] ; then
	gh-create-pr.sh
fi

if [[ "$ACTION_LIST" =~ "rm repository" ]] ; then
	find "$HOME/.m2/repository" -type d -name "*SNAPSHOT" -exec rm -rf {} \; 2> /dev/null
fi


