#!/bin/bash

set -eu

EXIT_CODE_BAD_DIR=1;
EXIT_CODE_MISSING_DEPENDENCY_COMMAND=2;
EXIT_CODE_OUTPUT_TS_FILE_NOT_FOUND=3;

if [ ! -f "package.json" ]; then
	echo "Can't found package.json file here. You must be on the root of an Angular project."
	exit "$EXIT_CODE_BAD_DIR";
fi

if [ ! -f "angular.json" ]; then
	echo "Can't found angular.json file here. You must be on the root of an Angular project."
	exit "$EXIT_CODE_BAD_DIR";
fi

if ! [ -x "$(command -v jq)" ]; then
	echo "Error: jq is not installed." >&2
	exit "$EXIT_CODE_MISSING_DEPENDENCY_COMMAND";
fi

######################################################

PROJECT_NAME=$(jq -r '.name' package.json);
SOURCE_ROOT=$(jq -r '.projects.'$PROJECT_NAME'.sourceRoot' angular.json);
SOURCE_PREFIX=$(jq -r '.projects.'$PROJECT_NAME'.prefix' angular.json);
SOURCE_DIR="$SOURCE_ROOT/$SOURCE_PREFIX";

if [ ! -d "$SOURCE_DIR" ]; then
	echo "Can't found dir \"$SOURCE_DIR\" based on \"$PROJECT_NAME\" and package.json/angular.json files."
	exit "$EXIT_CODE_BAD_DIR";
fi

######################################################

cmd=(whiptail --title "$PROJECT_NAME project" --menu "Which kind of artifact do you want to create?" 0 0 0);
cmd+=("component" "New component");
cmd+=("service" "New service");
cmd+=("enum" "New Enum");
cmd+=("pipe" "New Pipe");

set +e
TYPE_TO_CREATE=$("${cmd[@]}" 3>&1 1>&2 2>&3);
set -e

######################################################

set +u
if [ -z "$1" ]
then
	read -p "New $TYPE_TO_CREATE name [] " C
else
	C="$1";
fi
set -u

[ -z "$C" ] && echo "Cancel operation" && exit 0;

if [ "$TYPE_TO_CREATE" == "pipe" ]; then
	CMD_LINE="generate $TYPE_TO_CREATE $C --skip-tests";
else
	CMD_LINE="generate $TYPE_TO_CREATE $C --type $TYPE_TO_CREATE";
fi

if [ "$TYPE_TO_CREATE" == "component" ]; then
	read -p "Option inline-style ? [y/N] " INLINE_STYLE
	if [ "$INLINE_STYLE" == "y" ]; then
		CMD_LINE="$CMD_LINE --inline-style";
	fi
	
	read -p "Option inline-template ? [y/N] " INLINE_TEMPLATE
	if [ "$INLINE_TEMPLATE" == "y" ]; then
		CMD_LINE="$CMD_LINE --inline-template";
	fi
	CMD_LINE="$CMD_LINE --skip-tests";
fi

if [ "$TYPE_TO_CREATE" == "component" ]; then
	CMD_LINE="$CMD_LINE --skip-tests";
fi

ng $CMD_LINE;

######################################################

LONG_PROJECT_NAME=$(jq -r '."long-project-name"' package.json);
COPYRIGHT_PROJECT_NAME=$(jq -r '."copyright-project-name"' package.json);

if [ "$LONG_PROJECT_NAME" == "null" ]; then
	echo "You should add \"long-project-name\" and \"copyright-project-name\" keys to package.json"
	exit 0;
fi

######################################################

DEST_ARTIFACT_PATH="$SOURCE_DIR/$TYPE_TO_CREATE""s";
mkdir -p "$DEST_ARTIFACT_PATH/";

if [ "$TYPE_TO_CREATE" == "component" ]; then
	NEW_ARTIFACT_CREATED_PATH=$(find $SOURCE_DIR -maxdepth 1 -mindepth 1 -type d -printf '%T@ %p\0' | sort -zk 1nr | sed -z 's/^[^ ]* //' | tr '\0' '\n' | head -n 1);
	mv "$NEW_ARTIFACT_CREATED_PATH" "$DEST_ARTIFACT_PATH/"

	CREATED_DIR_NAME=$(basename "$NEW_ARTIFACT_CREATED_PATH");
	DEST_ARTIFACT_PATH="$DEST_ARTIFACT_PATH/$CREATED_DIR_NAME";
	CSS_FILE="$DEST_ARTIFACT_PATH/$CREATED_DIR_NAME.$TYPE_TO_CREATE.css";
	HTML_FILE="$DEST_ARTIFACT_PATH/$CREATED_DIR_NAME.$TYPE_TO_CREATE.html";
	TS_FILE="$DEST_ARTIFACT_PATH/$CREATED_DIR_NAME.$TYPE_TO_CREATE.ts";
else
	CSS_FILE="";
	HTML_FILE="";
	NEW_ARTIFACT_CREATED_FILE=$(find $SOURCE_DIR -maxdepth 1 -mindepth 1 -type f -printf '%T@ %p\0' | sort -zk 1nr | sed -z 's/^[^ ]* //' | tr '\0' '\n' | head -n 1);
	mv "$NEW_ARTIFACT_CREATED_FILE" "$DEST_ARTIFACT_PATH/"
	TS_FILE=$(find $DEST_ARTIFACT_PATH -maxdepth 1 -mindepth 1 -type f -printf '%T@ %p\0' | sort -zk 1nr | sed -z 's/^[^ ]* //' | tr '\0' '\n' | head -n 1);
fi

######################################################

if [ -f "$CSS_FILE" ]; then
	create-licence-preamble "/*" " */" " * " "$LONG_PROJECT_NAME" "$COPYRIGHT_PROJECT_NAME" > "$0.temp"
	cat "$CSS_FILE" >> "$0.temp"
	rm -f "$CSS_FILE";
	mv "$0.temp" "$CSS_FILE";
fi

if [ -f "$HTML_FILE" ]; then
        create-licence-preamble '<!--' '-->' "    " "$LONG_PROJECT_NAME" "$COPYRIGHT_PROJECT_NAME" > "$0.temp"
        cat "$HTML_FILE" >> "$0.temp"
        rm -f "$HTML_FILE";
        mv "$0.temp" "$HTML_FILE";
fi

if [ ! -f "$TS_FILE" ]; then
	echo "Can't found moved TS file: $TS_FILE";
	exit "$EXIT_CODE_OUTPUT_TS_FILE_NOT_FOUND";
fi

create-licence-preamble "/*" " */" " * " "$LONG_PROJECT_NAME" "$COPYRIGHT_PROJECT_NAME" > "$0.temp"

cat "$TS_FILE" >> "$0.temp"
rm -f "$TS_FILE";
mv "$0.temp" "$TS_FILE";

exit 0;
